package com.ceres.project.permissions;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum UserPermissions {
    VIEW_DASHBOARD("VIEW DASHBOARD"),

    CREATE_JOB("CREATE JOB"),
    DELETE_JOB("DELETE JOB"),
    EDIT_JOB("EDIT JOB"),
    VIEW_JOB("VIEW JOB"),

    CREATE_BID("CREATE BID"),
    DELETE_BID("DELETE BID"),
    EDIT_BID("EDIT BID"),
    VIEW_BID("VIEW BID"),
    VIEW_ALL_BIDS("VIEW ALL BIDS"),

    CREATE_SKILL("CREATE SKILL"),
    DELETE_SKILL("DELETE SKILL"),
    EDIT_SKILL("EDIT SKILL"),
    VIEW_SKILL("VIEW SKILL"),

    CREATE_USER("CREATE USER"),
    DELETE_USER("DELETE USER"),
    EDIT_USER("EDIT USER"),
    VIEW_USER("VIEW USER"),
    VIEW_ALL_USERS("VIEW ALL USERS"),

    CREATE_OBJECTIVE_ASSESSMENT("CREATE OBJECTIVE ASSESSMENT"),
    EDIT_OBJECTIVE_ASSESSMENT("EDIT OBJECTIVE ASSESSMENT"),
    VIEW_OBJECTIVE_ASSESSMENT("VIEW OBJECTIVE ASSESSMENT"),
    DELETE_OBJECTIVE_ASSESSMENT("DELETE OBJECTIVE ASSESSMENT"),

    CREATE_STRUCTURED_ASSESSMENT("CREATE STRUCTURED ASSESSMENT"),
    EDIT_STRUCTURED_ASSESSMENT("EDIT STRUCTURED ASSESSMENT"),
    VIEW_STRUCTURED_ASSESSMENT("VIEW STRUCTURED ASSESSMENT"),
    DELETE_STRUCTURED_ASSESSMENT("DELETE STRUCTURED ASSESSMENT"),

    SCHEDULE_INTERVIEW("SCHEDULE INTERVIEW"),
    CONDUCT_INTERVIEW("CONDUCT INTERVIEW"),
    EDIT_INTERVIEW_SCHEDULE("EDIT INTERVIEW SCHEDULE"),
    VIEW_INTERVIEW_SCHEDULE("VIEW INTERVIEW SCHEDULE"),
    UPDATE_INTERVIEW_STATUS("UPDATE INTERVIEW STATUS"),

    CREATE_TAKE_HOME_ASSESSMENT("CREATE TAKE HOME ASSESSMENT"),
    EDIT_TAKE_HOME_ASSESSMENT("EDIT TAKE HOME ASSESSMENT"),
    VIEW_TAKE_HOME_ASSESSMENT("VIEW TAKE HOME ASSESSMENT"),
    DELETE_TAKE_HOME_ASSESSMENT("DELETE TAKE HOME ASSESSMENT"),

    CREATE_SUBMISSION("CREATE SUBMISSION"),
    DELETE_SUBMISSION("DELETE SUBMISSION"),
    EDIT_SUBMISSION("EDIT SUBMISSION"),
    VIEW_SUBMISSION("VIEW SUBMISSION"),
    VIEW_ALL_SUBMISSIONS("VIEW ALL SUBMISSIONS"),

    CREATE_ISSUE("CREATE ISSUE"),
    DELETE_ISSUE("DELETE ISSUE"),
    EDIT_ISSUE("EDIT ISSUE"),
    VIEW_ISSUE("VIEW ISSUE"),
    VIEW_ALL_ISSUES("VIEW ALL ISSUES"),

    CREATE_WALLET("CREATE WALLET"),
    DELETE_WALLET("DELETE WALLET"),
    EDIT_WALLET("EDIT WALLET"),
    VIEW_WALLET("VIEW WALLET"),
    VIEW_ALL_WALLETS("VIEW ALL WALLETS"),

    CREATE_NOTIFICATION("CREATE NOTIFICATION"),
    DELETE_NOTIFICATION("DELETE NOTIFICATION"),
    EDIT_NOTIFICATION("EDIT NOTIFICATION"),
    VIEW_NOTIFICATION("VIEW ALL NOTIFICATION"),

    CREATE_PROPOSAL("CREATE PROPOSAL"),
    DELETE_PROPOSAL("DELETE PROPOSAL"),
    EDIT_PROPOSAL("EDIT PROPOSAL"),
    VIEW_PROPOSAL("VIEW PROPOSAL"),

    CREATE_DELIVERABLE("CREATE DELIVERABLE"),
    DELETE_DELIVERABLE("DELETE DELIVERABLE"),
    EDIT_DELIVERABLE("EDIT DELIVERABLE"),
    VIEW_DELIVERABLE("VIEW DELIVERABLE"),
    VIEW_ALL_DELIVERABLES("VIEW DELIVERABLES"),

    CREATE_STACK("CREATE STACK"),
    DELETE_STACK("DELETE STACK"),
    EDIT_STACK("EDIT STACK"),
    VIEW_STACK("VIEW STACK"),

    CREATE_ROLE("CREATE ROLE"),
    DELETE_ROLE("DELETE ROLE"),
    EDIT_ROLE("EDIT ROLE"),
    VIEW_ROLE("VIEW ROLE"),
    VIEW_ALL_ROLES("VIEW ALL ROLES"),

    CREATE_INTERVIEW_GRADE("CREATE INTERVIEW GRADE"),
    EDIT_INTERVIEW_GRADE("EDIT INTERVIEW GRADE"),
    VIEW_INTERVIEW_GRADE("VIEW INTERVIEW GRADE"),
    DELETE_INTERVIEW_GRADE("DELETE INTERVIEW GRADE"),

    CREATE_GRADING("CREATE GRADING"),
    DELETE_GRADING("DELETE GRADING"),
    EDIT_GRADING("EDIT GRADING"),
    VIEW_GRADING("VIEW GRADING"),
    VIEW_ALL_GRADINGS("VIEW ALL GRADINGS"),

    CREATE_PERMISSION("CREATE PERMISSION"),
    DELETE_PERMISSION("DELETE PERMISSION"),
    EDIT_PERMISSION("EDIT PERMISSION"),
    VIEW_PERMISSION("VIEW PERMISSION"),
    APPROVE_COMPANY("Approve Company"),
    VIEW_ALL_PERMISSIONS("VIEW ALL PERMISSIONS"),
    TEST_TEST_TEST("TEST PERMISSIONS"),

    CREATE_MODERATOR("CREATE MODERATOR"),

    CAN_VIEW_TRANSACTIONS("CAN VIEW TRANSACTIONS");

    private final String permissionName;
}
